package pdf

import (
	"bytes"
	"fmt"

	"github.com/phpdave11/gofpdf"
)

type ExportFile struct {
	Title       string
	Subtitle    string
	GeneratedBy string

	Headers []string
	Rows    [][]any
}

type Config struct {
	FontPath string
	FontName string

	Orientation string
	PageSize    string
	Unit        string
}

func DefaultConfig() Config {
	return Config{
		FontPath:    "fonts/THSarabunNew.ttf",
		FontName:    "THSarabun",
		Orientation: "L",
		PageSize:    "A4",
		Unit:        "mm",
	}
}

func Generate(file ExportFile) ([]byte, error) {
	return GenerateWithConfig(
		file,
		DefaultConfig(),
	)
}

func GenerateWithConfig(
	file ExportFile,
	cfg Config,
) ([]byte, error) {
	if cfg.FontName == "" {
		cfg.FontName = "THSarabun"
	}

	if cfg.FontPath == "" {
		cfg.FontPath = "fonts/THSarabunNew.ttf"
	}

	if cfg.Orientation == "" {
		cfg.Orientation = "L"
	}

	if cfg.PageSize == "" {
		cfg.PageSize = "A4"
	}

	if cfg.Unit == "" {
		cfg.Unit = "mm"
	}

	p := gofpdf.New(
		cfg.Orientation,
		cfg.Unit,
		cfg.PageSize,
		"",
	)

	p.AddUTF8Font(
		cfg.FontName,
		"",
		cfg.FontPath,
	)

	p.SetFont(
		cfg.FontName,
		"",
		14,
	)

	p.SetMargins(10, 10, 10)
	p.SetAutoPageBreak(false, 10)

	p.AddPage()

	drawFirstPageHeader(p, file, cfg)
	drawTable(p, file, cfg)

	var buf bytes.Buffer

	if err := p.Output(&buf); err != nil {
		return nil, fmt.Errorf("output pdf: %w", err)
	}

	return buf.Bytes(), nil
}

func drawFirstPageHeader(
	p *gofpdf.Fpdf,
	file ExportFile,
	cfg Config,
) {
	p.SetFont(cfg.FontName, "", 20)

	if file.Title != "" {
		p.CellFormat(
			0,
			10,
			file.Title,
			"",
			1,
			"C",
			false,
			0,
			"",
		)
	}

	if file.Subtitle != "" {
		p.SetFont(cfg.FontName, "", 14)

		p.CellFormat(
			0,
			8,
			file.Subtitle,
			"",
			1,
			"C",
			false,
			0,
			"",
		)
	}

	if file.GeneratedBy != "" {
		p.SetFont(cfg.FontName, "", 12)

		p.CellFormat(
			0,
			8,
			"Generated By: "+file.GeneratedBy,
			"",
			1,
			"R",
			false,
			0,
			"",
		)
	}

	p.Ln(4)
}

func drawTable(
	p *gofpdf.Fpdf,
	file ExportFile,
	cfg Config,
) {
	if len(file.Headers) == 0 {
		return
	}

	colWidths := calculateColumnWidths(
		p,
		len(file.Headers),
	)

	drawTableHeader(
		p,
		file.Headers,
		colWidths,
		cfg,
	)

	for _, row := range file.Rows {
		rowHeight := 8.0

		if shouldAddPage(p, rowHeight) {
			p.AddPage()

			drawTableHeader(
				p,
				file.Headers,
				colWidths,
				cfg,
			)
		}

		drawTableRow(
			p,
			row,
			colWidths,
			rowHeight,
			cfg,
		)
	}
}

func drawTableHeader(
	p *gofpdf.Fpdf,
	headers []string,
	colWidths []float64,
	cfg Config,
) {
	p.SetFont(cfg.FontName, "", 14)

	for i, header := range headers {
		p.CellFormat(
			colWidths[i],
			8,
			header,
			"1",
			0,
			"C",
			false,
			0,
			"",
		)
	}

	p.Ln(-1)
}

func drawTableRow(
	p *gofpdf.Fpdf,
	row []any,
	colWidths []float64,
	rowHeight float64,
	cfg Config,
) {
	p.SetFont(cfg.FontName, "", 13)

	for i := range colWidths {
		value := ""

		if i < len(row) {
			value = fmt.Sprint(row[i])
		}

		p.CellFormat(
			colWidths[i],
			rowHeight,
			value,
			"1",
			0,
			"L",
			false,
			0,
			"",
		)
	}

	p.Ln(-1)
}

func calculateColumnWidths(
	p *gofpdf.Fpdf,
	columnCount int,
) []float64 {
	pageWidth, _ := p.GetPageSize()
	left, _, right, _ := p.GetMargins()

	usableWidth := pageWidth - left - right
	colWidth := usableWidth / float64(columnCount)

	widths := make([]float64, columnCount)

	for i := range widths {
		widths[i] = colWidth
	}

	return widths
}

func shouldAddPage(
	p *gofpdf.Fpdf,
	nextRowHeight float64,
) bool {
	_, pageHeight := p.GetPageSize()
	_, _, _, bottom := p.GetMargins()

	return p.GetY()+nextRowHeight > pageHeight-bottom
}

// how to
// pdfBytes, err := pdf.Generate(pdf.ExportFile{
// 	Title:       "Historical Data",
// 	Subtitle:    "รายงานข้อมูลย้อนหลัง",
// 	GeneratedBy: "system",
// 	Headers: []string{
// 		"เลขที่บัญชี",
// 		"ชื่อลูกค้า",
// 		"หลักทรัพย์",
// 		"จำนวน",
// 		"ราคา",
// 		"มูลค่า",
// 	},
// 	Rows: [][]any{
// 		{"123-6", "สมชาย ใจดี", "AOT", 100, 62.50, 6250},
// 		{"456-7", "สมหญิง รักดี", "PTT", 50, 30.00, 1500},
// 	},
// })
// if err != nil {
// 	return err
// }

// c.Set("Content-Type", "application/pdf")
// c.Set("Content-Disposition", `attachment; filename="report.pdf"`)

// return c.Send(pdfBytes)
